package bitboard

const (
	HORIZONTAL_MASK = uint8(iota)
	NOT_HORIZONTAL_MASK
	VERTICAL_MASK
	NOT_VERTICAL_MASK
	LRTB_MASK
	NOT_LRTB_MASK
	LRBT_MASK
	NOT_LRBT_MASK
	DIRECTIONAL_MASK
	NOT_DIRECTIONAL_MASK
	MINER_MASK
	NOT_MINER_MASK
	NEARBY_MASK
	NOT_NEARBY_MASK
	ZOMBIE_NEAR_MASK
	NOT_ZOMBIE_NEAR_MASK
	ZOMBIE_FAR_MASK
	NOT_ZOMBIE_FAR_MASK
	SENTINEL_MASK
	NOT_SENTINEL_MASK
	CATAPULT_MASK
	NOT_CATAPULT_MASK
)
